// import React from 'react'

// export default function Metrics( {customization = {}}) {
//   const primaryColor = customization.primaryColor || '#4CAF50'; // اللون الأساسي
//   const secondaryColor = customization.secondaryColor || '#2C3E50'; // اللون الثانوي
//   const accentColor = customization.accentColor || '#FFC107'; // اللون المميز
//   const backgroundColor = customization.backgroundColor || '#FFFFFF'; // لون الخلفية
//   const fontFamily = customization.fontFamily || 'sans-serif'; // نوع الخط
//   const isActive = customization.isActive ?? true; // هل التخصيص مفعل؟
//     return (
        
//             <div className="relative font-[sans-serif] before:absolute before:w-full before:h-full before:inset-0 before:bg-black before:opacity-60 before:z-10">
//       <img src="https://readymadeui.com/cardImg.webp" alt="Banner Image" className="absolute inset-0 w-full h-full object-cover" />
//       <div className="min-h-[370px] relative z-50 h-full max-w-6xl mx-auto flex flex-col justify-center items-center text-center px-4 py-8">
//         <h2 className="text-4xl font-bold mb-14 text-center text-white">Application Metrics</h2>
//         <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
//           <div className="text-center">
//             <h3 className="text-white text-[38px] font-bold" style={{ secondaryColor }}>5.4M+</h3>
//             <p className="text-base text-gray-400 font-bold mt-3">Total Users</p>
//             <p className="leading-relaxed text-sm text-gray-200 mt-2">The total number of registered users on the platform.</p>
//           </div>
//           <div className="text-center">
//             <h3 className="text-white text-[38px] font-bold" style={{ secondaryColor }}>$80K</h3>
//             <p className="text-base text-gray-400 font-bold mt-3">Revenue</p>
//             <p className="leading-relaxed text-sm text-gray-200 mt-2">The total revenue generated by the application.</p>
//           </div>
//           <div className="text-center">
//             <h3 className="text-white text-[38px] font-bold" style={{ secondaryColor }} >100K</h3>
//             <p className="text-base text-gray-400 font-bold mt-3">Engagement</p>
//             <p className="leading-relaxed text-sm text-gray-200 mt-2">The level of user engagement with the applications content and features.</p>
//           </div>
//           <div className="text-center">
//             <h3 className="text-white text-[38px] font-bold" style={{ secondaryColor }} >99.9%</h3>
//             <p className="text-base text-gray-400 font-bold mt-3">Server Uptime</p>
//             <p className="leading-relaxed text-sm text-gray-200 mt-2">The percentage of time the server has been operational and available.</p>
//           </div>
//         </div>
//       </div>
//     </div>
        
//     )
// }

import React from 'react';

export default function Metrics({ customization = {} }) {
  // تخصيص الألوان والخطوط بناءً على القيم الممررة
  const primaryColor = customization.primaryColor || '#4CAF50'; // اللون الأساسي
  const secondaryColor = customization.secondaryColor || '#2C3E50'; // اللون الثانوي
  const accentColor = customization.accentColor || '#FFC107'; // اللون المميز
  const backgroundColor = customization.backgroundColor || '#FFFFFF'; // لون الخلفية
  const fontFamily = customization.fontFamily || 'sans-serif'; // نوع الخط
  const isActive = customization.isActive ?? true; // هل التخصيص مفعل؟

  return (
    <div className="relative font-[sans-serif] before:absolute before:w-full before:h-full before:inset-0 before:bg-black before:opacity-60 before:z-10">
      <img
        src="https://readymadeui.com/cardImg.webp"
        alt="Banner Image"
        className="absolute inset-0 w-full h-full object-cover"
      />
      <div className="min-h-[370px] relative z-50 h-full max-w-6xl mx-auto flex flex-col justify-center items-center text-center px-4 py-8">
        <h2 className="text-4xl font-bold mb-14 text-center text-white" style={{ fontFamily }}>
          Application Metrics
        </h2>
        <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
          <div className="text-center">
            <h3 className="text-white text-[38px] font-bold" style={{ color: accentColor }}>
              5.4M+
            </h3>
            <p className="text-base text-gray-400 font-bold mt-3">Total Users</p>
            <p className="leading-relaxed text-sm text-gray-200 mt-2">
              The total number of registered users on the platform.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-white text-[38px] font-bold" style={{ color: accentColor }}>
              $80K
            </h3>
            <p className="text-base text-gray-400 font-bold mt-3">Revenue</p>
            <p className="leading-relaxed text-sm text-gray-200 mt-2">
              The total revenue generated by the application.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-white text-[38px] font-bold" style={{ color: accentColor }}>
              100K
            </h3>
            <p className="text-base text-gray-400 font-bold mt-3">Engagement</p>
            <p className="leading-relaxed text-sm text-gray-200 mt-2">
              The level of user engagement with the application s content and features.
            </p>
          </div>
          <div className="text-center">
            <h3 className="text-white text-[38px] font-bold" style={{ color: backgroundColor }}>
              99.9%
            </h3>
            <p className="text-base text-gray-400 font-bold mt-3">Server Uptime</p>
            <p className="leading-relaxed text-sm text-gray-200 mt-2">
              The percentage of time the server has been operational and available.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
