// scripts/convert-font.js
const { readFileSync, writeFileSync } = require('fs')
const path = require('path')

const fontPath = path.resolve(__dirname, '../public/fonts/IBMPlexArabic-Regular.ttf')
const fontData = readFileSync(fontPath)
const base64 = fontData.toString('base64')

const out = `// generated by scripts/convert-font.js
export const ibmPlexArabic = '${base64}'
`

writeFileSync(path.resolve(__dirname, '../lib/arabicFont.js'), out)
console.log('✔ arabicFont.js generated.')
